// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantService.Data;

#nullable disable

namespace PlantService.Migrations
{
    [DbContext(typeof(PlantContext))]
    [Migration("20260325194123_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantService.Models.PlantCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("GachaWeight")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LatinName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LightPreference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaterNeeds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Rarity");

                    b.ToTable("PlantCatalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A hardy trailing vine that thrives on neglect. Perfect for beginners.",
                            Emoji = "🌿",
                            GachaWeight = 100,
                            IsActive = true,
                            LatinName = "Epipremnum aureum",
                            LightPreference = "Low",
                            Name = "Pothos",
                            Rarity = "Common",
                            WaterNeeds = "Low"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Produces cute baby plants on long stems. Great air purifier.",
                            Emoji = "🌱",
                            GachaWeight = 100,
                            IsActive = true,
                            LatinName = "Chlorophytum comosum",
                            LightPreference = "Indirect",
                            Name = "Spider Plant",
                            Rarity = "Common",
                            WaterNeeds = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sword-like leaves that practically thrive on neglect.",
                            Emoji = "🪴",
                            GachaWeight = 100,
                            IsActive = true,
                            LatinName = "Sansevieria trifasciata",
                            LightPreference = "Low",
                            Name = "Snake Plant",
                            Rarity = "Common",
                            WaterNeeds = "Low"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic cactus with paddle-shaped segments.",
                            Emoji = "🌵",
                            GachaWeight = 100,
                            IsActive = true,
                            LatinName = "Opuntia",
                            LightPreference = "Direct",
                            Name = "Prickly Pear",
                            Rarity = "Common",
                            WaterNeeds = "Low"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lush, feathery fronds that love humidity.",
                            Emoji = "🌿",
                            GachaWeight = 50,
                            IsActive = true,
                            LatinName = "Nephrolepis exaltata",
                            LightPreference = "Indirect",
                            Name = "Fern",
                            Rarity = "Uncommon",
                            WaterNeeds = "High"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant white blooms that brighten any room.",
                            Emoji = "🌼",
                            GachaWeight = 50,
                            IsActive = true,
                            LatinName = "Spathiphyllum",
                            LightPreference = "Low",
                            Name = "Peace Lily",
                            Rarity = "Uncommon",
                            WaterNeeds = "Medium"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A whimsical fungi friend for your collection.",
                            Emoji = "🍄",
                            GachaWeight = 50,
                            IsActive = true,
                            LatinName = "Amanita muscaria",
                            LightPreference = "Low",
                            Name = "Red Mushroom",
                            Rarity = "Uncommon",
                            WaterNeeds = "High"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A tropical beauty with dramatic split leaves. Loves humidity and indirect light.",
                            Emoji = "🌿",
                            GachaWeight = 25,
                            IsActive = true,
                            LatinName = "Monstera deliciosa",
                            LightPreference = "Indirect",
                            Name = "Monstera",
                            Rarity = "Rare",
                            WaterNeeds = "Medium"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Large violin-shaped leaves make this a statement piece.",
                            Emoji = "🌳",
                            GachaWeight = 25,
                            IsActive = true,
                            LatinName = "Ficus lyrata",
                            LightPreference = "Bright",
                            Name = "Fiddle Leaf Fig",
                            Rarity = "Rare",
                            WaterNeeds = "Medium"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cascading strings of bead-like leaves.",
                            Emoji = "💮",
                            GachaWeight = 25,
                            IsActive = true,
                            LatinName = "Senecio rowleyanus",
                            LightPreference = "Bright",
                            Name = "String of Pearls",
                            Rarity = "Rare",
                            WaterNeeds = "Low"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delicate pink blooms that symbolize renewal and hope.",
                            Emoji = "🌸",
                            GachaWeight = 10,
                            IsActive = true,
                            LatinName = "Prunus serrulata",
                            LightPreference = "Bright",
                            Name = "Cherry Blossom",
                            Rarity = "Epic",
                            WaterNeeds = "Medium"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exotic blooms that look like tropical birds in flight.",
                            Emoji = "🌺",
                            GachaWeight = 10,
                            IsActive = true,
                            LatinName = "Strelitzia reginae",
                            LightPreference = "Direct",
                            Name = "Bird of Paradise",
                            Rarity = "Epic",
                            WaterNeeds = "Medium"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A magical tree with bark that peels to reveal rainbow colors.",
                            Emoji = "🌈",
                            GachaWeight = 3,
                            IsActive = true,
                            LatinName = "Eucalyptus deglupta",
                            LightPreference = "Direct",
                            Name = "Rainbow Eucalyptus",
                            Rarity = "Legendary",
                            WaterNeeds = "High"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The rarest bloom in the world. Smells terrible but looks amazing!",
                            Emoji = "🥀",
                            GachaWeight = 2,
                            IsActive = true,
                            LatinName = "Amorphophallus titanum",
                            LightPreference = "Indirect",
                            Name = "Corpse Flower",
                            Rarity = "Legendary",
                            WaterNeeds = "High"
                        });
                });

            modelBuilder.Entity("PlantService.Models.UserPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrowthProgress")
                        .HasColumnType("integer");

                    b.Property<int>("GrowthStage")
                        .HasColumnType("integer");

                    b.Property<bool>("InGreenhouse")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCaredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastDecayAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NutrientLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PlantCatalogId")
                        .HasColumnType("integer");

                    b.Property<int>("SunlightLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantCatalogId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PlantCatalogId");

                    b.ToTable("UserPlants");
                });

            modelBuilder.Entity("PlantService.Models.UserPlant", b =>
                {
                    b.HasOne("PlantService.Models.PlantCatalog", "PlantCatalog")
                        .WithMany("UserPlants")
                        .HasForeignKey("PlantCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantCatalog");
                });

            modelBuilder.Entity("PlantService.Models.PlantCatalog", b =>
                {
                    b.Navigation("UserPlants");
                });
#pragma warning restore 612, 618
        }
    }
}
